### ISSUE TITLE
Make faq easier to write and move it to the sample app

### ISSUE THREAD

**Issue by AllanWang** [jahirfiquitiva/IconShowcase#114]
Rather than two array lists, make it so that each item is

<item>Question String here|Answer String here</item>

or use an xml parser

**Comment by jahirfiquitiva** [comment]
I will say no to this, just because:
1. People have never asked me for a way to add more questions.
2. I already asked the people in the community and many icon pack designers about their FAQs and they are already included.
3. Current way allows translations. There are users all around the world.

Thanks anyways Allan :)
