### ISSUE TITLE
Issues after generating signed APK

### ISSUE THREAD

**Issue by a-random-package** [jahirfiquitiva/IconShowcase#134]
Most of the icons are black squares after the user applies the theme. This doesn't happen at all when I run the app from Studio to my emulators/devices. Has this happened before?

**Comment by jahirfiquitiva** [comment]
Check this lines:
https://github.com/jahirfiquitiva/IconShowcase-Dashboard/blob/master/sample/build.gradle#L43

Make sure shrinkResources is set to false. If issue is still present, then disable minifyEnabled.

Finally, are you using dashboard or library source?

**Comment by jahirfiquitiva** [comment]
Let me know if it fixed the issue, or it persists.

**Comment by AllanWang** [comment]
Definitely a proguard issue.

**Comment by a-random-package** [comment]
Neither option worked. I am using the library source.

**Comment by jahirfiquitiva** [comment]
@a-random-package 

That's weird, I'm almost sure it is a proguard issue.

Now that you said you're using the library source, you might want to check [these lines](https://github.com/jahirfiquitiva/IconShowcase/blob/master/app/build.gradle#L71)

Be sure to rebuild the project when doing changes. Try completely reinstalling the app.

Be sure to read the [Wiki](https://github.com/jahirfiquitiva/IconShowcase-Dashboard/wiki/)

And finally be sure to [read this](https://github.com/jahirfiquitiva/IconShowcase#library-source) because this is all the support I will provide, because you're using the library source.

Good luck. And thanks for using IconShowcase.

**Comment by a-random-package** [comment]
Thank you for your quick response. Would it be unwise to remove proguard altogether?

**Comment by jahirfiquitiva** [comment]
@a-random-package 

You can try removing the lines `minifyEnabled` and `shrinkResources` ... but the `proguard-rules.pro` file is needed to keep some important things in code.

You could remove it yeah, but as mentioned [here](https://github.com/jahirfiquitiva/IconShowcase#library-source) under your own risk and responsibility.

**Comment by a-random-package** [comment]
Removing those lines didn't fix the issue either. I'll put in some time googling proguard issues. Thanks again for the assistance.
