### ISSUE TITLE
Spaces are displayed as '_' at Icon Request tab.

### ISSUE THREAD

**Issue by chocomilk-dev** [jahirfiquitiva/IconShowcase#153]
![screenshot_20171025-091439](https://user-images.githubusercontent.com/26513366/31974202-159f51f6-b965-11e7-81a5-9cbdcee3d36e.png)

**Comment by jahirfiquitiva** [comment]
Hi

I'm sorry about this issue, but IconShowcase is not maintained right now.
I'm working on a completely new version so I'm focusing on that instead of working on the old one.

Please kindly wait until the release of the new version since this is just a minor issue that doesn't affect performance or stability.

You can join the [Google+ Community](https://plus.google.com/communities/117748118619432374563) to stay tuned about next update.
