### ISSUE TITLE
It shows header on the tab when I change the device dpi.

### ISSUE THREAD

**Issue by chocomilk-dev** [jahirfiquitiva/IconShowcase#154]
![screenshot_20171025-091803](https://user-images.githubusercontent.com/26513366/31974285-db687ffc-b965-11e7-8be6-c7c0489bb1c0.png)
![screenshot_20171025-092315](https://user-images.githubusercontent.com/26513366/31974348-342b3148-b966-11e7-9a81-9674e019f152.png)
![screenshot_20171025-092308](https://user-images.githubusercontent.com/26513366/31974349-345527aa-b966-11e7-834b-3775b1e41f40.png)

**Comment by jahirfiquitiva** [comment]
Hi

I'm sorry about this issue, but IconShowcase is not maintained right now.
I'm working on a completely new version so I'm focusing on that instead of working on the old one.

Please kindly wait until the release of the new version since this is just a minor issue that doesn't affect performance or stability.

You can join the [Google+ Community](https://plus.google.com/communities/117748118619432374563) to stay tuned about next update.
